name: tunner
on: [push]
jobs:
  run:

    runs-on: ubuntu-latest
            
    steps:
      - uses: actions/checkout@v3
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Install dependencies
      
        run: |
          pip install -r requirements.txt
      - name: Run tunner
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          LOCATION: ${{ secrets.LOCATION }}
          BUCKET: ${{ secrets.BUCKET }}
          DISPLAY_NAME: ${{ secrets.DISPLAY_NAME }}
          CONTAINER_URI: ${{ secrets.CONTAINER_URI }}
          TRAIN_VERSION: ${{ secrets.TRAIN_VERSION }}
          TRAIN_IMAGE: ${{ secrets.TRAIN_IMAGE }}
          MODEL_DIR: ${{ secrets.MODEL_DIR }}
          DATASET_DIR: ${{ secrets.DATASET_DIR }}
        run: |
          python hp_tunning_runner.py
