name: Tunner-Test
on: [push]
jobs:
  tunner-test:
    runs-on: ubuntu-latest
    needs: trainer-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Create tar file
        run: |
          tar cvf trainer_boston.tar custom

      - name: Compress tar file
        run: |
          gzip trainer_boston.tar
          
      - name: Google authenication
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}' # Replace with the name of your GitHub Actions secret

      - name: Upload folder
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'trainer_boston.tar.gz'
          destination: 'ml-coding'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run hyperparameter tunning
        run: |
          python hp_tunning_runner.py

          
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'
      # - name: Test Trainer Task
      #   working-directory: ./custom
