name: Tunner-Test
on: [push]
jobs:
  tunner-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test trainer task
        working-directory: ./custom
        run: pip install -e . && python -m trainer.task --run_locally=True
        
      - name: Create tar file
        run: |
          tar cvf trainer_boston.tar custom
          
      - name: Google authenication
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}' # Replace with the name of your GitHub Actions secret

      - name: Upload folder
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'trainer_boston.tar'
          destination: 'ml-coding'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # - name: Run hyperparameter tunning
      #   run: |
      #     python hp_tunning_runner.py

      # - name: Deployment
      #   run: |
      #     python deployment_runner.py

      - name: Test end point 
        run: |
          python test_endpoint_prediction.py
          
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'
      # - name: Test Trainer Task
      #   working-directory: ./custom
